// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface PortInfo {
  port: number;
  pid: number;
  procName: string;
  project: string;
}

export function Greet(arg1: string): Promise<string>;

export function IsAdmin(): Promise<boolean>;

export function ScanPorts(): Promise<PortInfo[]>;

export function KillPid(pid: number): Promise<void>;

export function Hash(algorithm: string, text: string): Promise<string>;

export function Hmac(algorithm: string, text: string, key: string): Promise<string>;

export function BcryptHash(password: string, cost: number): Promise<string>;

export function BcryptCompare(password: string, hashed: string): Promise<boolean>;

export function AESEncrypt(plaintext: string, key: string): Promise<string>;

export function AESDecrypt(ciphertextB64: string, key: string): Promise<string>;

export function DesEncrypt(plaintext: string, key: string): Promise<string>;

export function DesDecrypt(ciphertextB64: string, key: string): Promise<string>;

export function RSAGenerateKey(): Promise<string>;

export function RSAEncrypt(plaintext: string, publicKeyPEM: string): Promise<string>;

export function RSADecrypt(ciphertextB64: string, privateKeyPEM: string): Promise<string>;

export function Base64Encode(text: string): Promise<string>;

export function Base64Decode(text: string): Promise<string>;

export function HexEncode(text: string): Promise<string>;

export function HexDecode(text: string): Promise<string>;

export function URLEncode(text: string): Promise<string>;

export function URLDecode(text: string): Promise<string>;

export interface TOTPSecret {
  name: string;
  secret: string;
  issuer: string;
}

export interface TOTPCode {
  name: string;
  issuer: string;
  code: string;
  remain: number;
}

export function TOTPAddSecret(name: string, secret: string, issuer: string): Promise<void>;

export function TOTPListSecrets(): Promise<TOTPSecret[]>;

export function TOTPDeleteSecret(name: string): Promise<void>;

export function TOTPGenerateAll(): Promise<TOTPCode[]>;

export function TOTPIsPasswordSet(): Promise<boolean>;

export function TOTPSetupPassword(password: string): Promise<void>;

export function TOTPUnlock(password: string): Promise<boolean>;

export function TOTPLock(): Promise<void>;

export function TOTPIsUnlocked(): Promise<boolean>;
