// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function IsAdmin() {
    return window['go']['main']['App']['IsAdmin']();
}

export function ScanPorts() {
    return window['go']['main']['App']['ScanPorts']();
}

export function KillPid(pid) {
    return window['go']['main']['App']['KillPid'](pid);
}

export function Hash(algorithm, text) {
    return window['go']['main']['App']['Hash'](algorithm, text);
}

export function Hmac(algorithm, text, key) {
    return window['go']['main']['App']['Hmac'](algorithm, text, key);
}

export function BcryptHash(password, cost) {
    return window['go']['main']['App']['BcryptHash'](password, cost);
}

export function BcryptCompare(password, hashed) {
    return window['go']['main']['App']['BcryptCompare'](password, hashed);
}

export function AESEncrypt(plaintext, key) {
    return window['go']['main']['App']['AESEncrypt'](plaintext, key);
}

export function AESDecrypt(ciphertextB64, key) {
    return window['go']['main']['App']['AESDecrypt'](ciphertextB64, key);
}

export function DesEncrypt(plaintext, key) {
    return window['go']['main']['App']['DesEncrypt'](plaintext, key);
}

export function DesDecrypt(ciphertextB64, key) {
    return window['go']['main']['App']['DesDecrypt'](ciphertextB64, key);
}

export function RSAGenerateKey() {
    return window['go']['main']['App']['RSAGenerateKey']();
}

export function RSAEncrypt(plaintext, publicKeyPEM) {
    return window['go']['main']['App']['RSAEncrypt'](plaintext, publicKeyPEM);
}

export function RSADecrypt(ciphertextB64, privateKeyPEM) {
    return window['go']['main']['App']['RSADecrypt'](ciphertextB64, privateKeyPEM);
}

export function Base64Encode(text) {
    return window['go']['main']['App']['Base64Encode'](text);
}

export function Base64Decode(text) {
    return window['go']['main']['App']['Base64Decode'](text);
}

export function HexEncode(text) {
    return window['go']['main']['App']['HexEncode'](text);
}

export function HexDecode(text) {
    return window['go']['main']['App']['HexDecode'](text);
}

export function URLEncode(text) {
    return window['go']['main']['App']['URLEncode'](text);
}

export function URLDecode(text) {
    return window['go']['main']['App']['URLDecode'](text);
}

export function TOTPAddSecret(name, secret, issuer) {
    return window['go']['main']['App']['TOTPAddSecret'](name, secret, issuer);
}

export function TOTPListSecrets() {
    return window['go']['main']['App']['TOTPListSecrets']();
}

export function TOTPDeleteSecret(name) {
    return window['go']['main']['App']['TOTPDeleteSecret'](name);
}

export function TOTPGenerateAll() {
    return window['go']['main']['App']['TOTPGenerateAll']();
}

export function TOTPIsPasswordSet() {
    return window['go']['main']['App']['TOTPIsPasswordSet']();
}

export function TOTPSetupPassword(password) {
    return window['go']['main']['App']['TOTPSetupPassword'](password);
}

export function TOTPUnlock(password) {
    return window['go']['main']['App']['TOTPUnlock'](password);
}

export function TOTPLock() {
    return window['go']['main']['App']['TOTPLock']();
}

export function TOTPIsUnlocked() {
    return window['go']['main']['App']['TOTPIsUnlocked']();
}
