// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AESDecrypt(arg1, arg2) {
  return window['go']['main']['App']['AESDecrypt'](arg1, arg2);
}

export function AESEncrypt(arg1, arg2) {
  return window['go']['main']['App']['AESEncrypt'](arg1, arg2);
}

export function Base64Decode(arg1) {
  return window['go']['main']['App']['Base64Decode'](arg1);
}

export function Base64Encode(arg1) {
  return window['go']['main']['App']['Base64Encode'](arg1);
}

export function BcryptCompare(arg1, arg2) {
  return window['go']['main']['App']['BcryptCompare'](arg1, arg2);
}

export function BcryptHash(arg1, arg2) {
  return window['go']['main']['App']['BcryptHash'](arg1, arg2);
}

export function DesDecrypt(arg1, arg2) {
  return window['go']['main']['App']['DesDecrypt'](arg1, arg2);
}

export function DesEncrypt(arg1, arg2) {
  return window['go']['main']['App']['DesEncrypt'](arg1, arg2);
}

export function Hash(arg1, arg2) {
  return window['go']['main']['App']['Hash'](arg1, arg2);
}

export function HexDecode(arg1) {
  return window['go']['main']['App']['HexDecode'](arg1);
}

export function HexEncode(arg1) {
  return window['go']['main']['App']['HexEncode'](arg1);
}

export function Hmac(arg1, arg2, arg3) {
  return window['go']['main']['App']['Hmac'](arg1, arg2, arg3);
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function KillPid(arg1) {
  return window['go']['main']['App']['KillPid'](arg1);
}

export function KillPort(arg1) {
  return window['go']['main']['App']['KillPort'](arg1);
}

export function RSADecrypt(arg1, arg2) {
  return window['go']['main']['App']['RSADecrypt'](arg1, arg2);
}

export function RSAEncrypt(arg1, arg2) {
  return window['go']['main']['App']['RSAEncrypt'](arg1, arg2);
}

export function RSAGenerateKey() {
  return window['go']['main']['App']['RSAGenerateKey']();
}

export function ScanPorts() {
  return window['go']['main']['App']['ScanPorts']();
}

export function TOTPAddSecret(arg1, arg2, arg3) {
  return window['go']['main']['App']['TOTPAddSecret'](arg1, arg2, arg3);
}

export function TOTPDeleteSecret(arg1) {
  return window['go']['main']['App']['TOTPDeleteSecret'](arg1);
}

export function TOTPGenerateAll() {
  return window['go']['main']['App']['TOTPGenerateAll']();
}

export function TOTPIsPasswordSet() {
  return window['go']['main']['App']['TOTPIsPasswordSet']();
}

export function TOTPIsUnlocked() {
  return window['go']['main']['App']['TOTPIsUnlocked']();
}

export function TOTPListSecrets() {
  return window['go']['main']['App']['TOTPListSecrets']();
}

export function TOTPLock() {
  return window['go']['main']['App']['TOTPLock']();
}

export function TOTPSetupPassword(arg1) {
  return window['go']['main']['App']['TOTPSetupPassword'](arg1);
}

export function TOTPUnlock(arg1) {
  return window['go']['main']['App']['TOTPUnlock'](arg1);
}

export function URLDecode(arg1) {
  return window['go']['main']['App']['URLDecode'](arg1);
}

export function URLEncode(arg1) {
  return window['go']['main']['App']['URLEncode'](arg1);
}
