// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AESDecrypt(arg1:string,arg2:string):Promise<string>;

export function AESEncrypt(arg1:string,arg2:string):Promise<string>;

export function Base64Decode(arg1:string):Promise<string>;

export function Base64Encode(arg1:string):Promise<string>;

export function BcryptCompare(arg1:string,arg2:string):Promise<boolean>;

export function BcryptHash(arg1:string,arg2:number):Promise<string>;

export function DesDecrypt(arg1:string,arg2:string):Promise<string>;

export function DesEncrypt(arg1:string,arg2:string):Promise<string>;

export function Hash(arg1:string,arg2:string):Promise<string>;

export function HexDecode(arg1:string):Promise<string>;

export function HexEncode(arg1:string):Promise<string>;

export function Hmac(arg1:string,arg2:string,arg3:string):Promise<string>;

export function IsAdmin():Promise<boolean>;

export function KillPid(arg1:number):Promise<void>;

export function KillPort(arg1:number):Promise<void>;

export function RSADecrypt(arg1:string,arg2:string):Promise<string>;

export function RSAEncrypt(arg1:string,arg2:string):Promise<string>;

export function RSAGenerateKey():Promise<string>;

export function ScanPorts():Promise<Array<main.PortInfo>>;

export function TOTPAddSecret(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TOTPDeleteSecret(arg1:string):Promise<void>;

export function TOTPGenerateAll():Promise<Array<main.TOTPCode>>;

export function TOTPIsPasswordSet():Promise<boolean>;

export function TOTPIsUnlocked():Promise<boolean>;

export function TOTPListSecrets():Promise<Array<main.TOTPSecret>>;

export function TOTPLock():Promise<void>;

export function TOTPSetupPassword(arg1:string):Promise<void>;

export function TOTPUnlock(arg1:string):Promise<boolean>;

export function URLDecode(arg1:string):Promise<string>;

export function URLEncode(arg1:string):Promise<string>;
